language: python
python:
  - "2.7"
before_install:
  - sudo apt-get install $(cat ubuntu_requirements)
install:
  - pip install zc.buildout
  - buildout init
  - buildout -c development.cfg
script:
  - bin/nose akorn.scrapers
  - bin/nose akorn.celery
  - bin/django test accounts
  - bin/django test api
  - bin/django test panes
  - bin/django test search
  - bin/django test simulator

